exclude: ^(explore/)|.pixi$
repos:
  - repo: local
    hooks:
      # ensure pixi environments are up to date
      - id: pixi-install
        name: pixi-install
        entry: pixi install -e default
        language: system
        always_run: true
        require_serial: true
        pass_filenames: false
      # ruff
      - id: ruff
        name: ruff
        entry: pixi run ruff check --fix --exit-non-zero-on-fix --force-exclude
        language: system
        types_or: [python, pyi]
        require_serial: true
      - id: ruff-format
        name: ruff-format
        entry: pixi run ruff format --force-exclude
        language: system
        types_or: [python, pyi]
        require_serial: true
      # mypy
      - id: mypy
        name: mypy
        entry: pixi run -e test mypy
        language: system
        types: [python]
        require_serial: true
      # typos
      - id: typos
        name: typos
        entry: pixi run typos --force-exclude
        language: system
        types: [text]
        require_serial: true