[project]
authors = [{name = "Maximilian Kruse", email = "maximilian.kruse@kit.edu"}]
maintainers = [{ name = "Maximilian Kruse", email = "maximilian.kruse@kit.edu" }]
description = "Large-Scale Gaussian Prior Fields via SPDEs"
name = "ls-prior"
requires-python = ">= 3.13"
dynamic = ["version"]
readme = "README.md"
license = { text = "MIT" }
keywords = ["prior-fields", "bayesian inference", "spde", "fenicsx"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Operating System :: POSIX :: Linux",
  "Programming Language :: Python :: 3",
  "Intended Audience :: Science/Research",
  "License :: OSI Approved :: MIT License",
]
urls = { repository = "https://github.com/UQatKIT/LS-Prior", documentation = "https://uqatkit.github.io/LS-Prior/" }


# --------------------------------------------------------------------------------------------------
dependencies = []

[tool.pixi.pypi-dependencies]
ls_prior = { path = ".", editable = true }


# --------------------------------------------------------------------------------------------------
[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.tasks]

[tool.pixi.dependencies]
beartype = "*"
numpy = "*"


# --------------------------------------------------------------------------------------------------
[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["ALL"]
ignore = [
  "COM812",
  "EM101",
  "EM102",
  "FBT001",
  "FBT003",
  "F722",
  "F821",
  "ISC001",
  "PD008",
  "PD011",
  "PLR2004",
  "PT003",
  "RET504",
  "S101",
  "TRY003",
]
pydocstyle.convention = "google"


# --------------------------------------------------------------------------------------------------
[tool.pytest.ini_options]
testpaths = ["test"]
addopts = [
  "-v",
  "--import-mode=importlib",
  "--cov=ls_prior",
  "--cov-config=.coveragerc",
]
markers = [
  "unit: unit tests",
  "integration: integration tests",
  "slow: tests with long runtime",
]
