name: Release
run-name: Create Github and Prefix release from tagged commit

# -- Trigger Events --------------------------------------------------------------------------------
on:
  workflow_dispatch:
  push:
    tags:
      - v*

# -- Concurrency -----------------------------------------------------------------------------------
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

# -- Jobs ------------------------------------------------------------------------------------------
jobs:
  # Create Github release with changelog
  release:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      contents: write
    steps:
      - name: Checkout code
        id: checkout-code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Install Pixi
        id: setup-pixi
        uses: prefix-dev/setup-pixi@v0.9.0
        with:
          cache: true
          locked: true
      - name: Install dependencies
        id: install-deps
        run: pixi install -e docs
      - name: Create changelog
        id: create-changelog
        run: pixi run -e docs changelog --latest --strip all --output ${{ github.workspace }}/changelog.md
      - name: Create release
        id: create-release
        uses: softprops/action-gh-release@v2
        with:
          body_path: ${{ github.workspace }}/changelog.md

  # Publish to personal prefix.dev channel
  publish:
    runs-on: ubuntu-latest
    environment: release
    needs: release
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout code
        id: checkout-code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Install Pixi
        id: setup-pixi
        uses: prefix-dev/setup-pixi@v0.9.0
        with:
          cache: true
          locked: true
      - name: Build package
        id: build-package
        run: pixi build
      - name: Install rattler-build
        id: install-rattler-build
        run: pixi global install rattler-build
      - name: Publish package
        id: publish-package
        run: |
          for pkg in $(find . -type f \( -name "*.conda" -o -name "*.tar.bz2" \) ); do
            echo "Uploading ${pkg}"
            rattler-build upload prefix -c kruse-forge "${pkg}" --api-key=${{ secrets.PREFIX_API_KEY }}
          done